version: "3.9"

services:
  web:
    build: .
    container_name: py-fmg-app
    ports:
      - "9888:8000"
    volumes:
      - .:/app
    env_file:
      - .env # add db URL case dockerbuild
    depends_on:
      - db

  db:
    image: postgis/postgis:14-3.3
    container_name: py-fmg-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
