#!/usr/bin/env python3
"""Test AleaPRNG compatibility with FMG JavaScript implementation."""

import sys
from pathlib import Path
sys.path.append(str(Path(__file__).parent))

from py_fmg.core.alea_prng import AleaPRNG

# Expected values from FMG JavaScript with seed 'debug-123'
# These values were generated by running the following in FMG browser console:
# prng = new Alea('debug-123');
# values = [];
# for (let i = 0; i < 1000; i++) values.push(prng());
# console.log(JSON.stringify(values));

# First 100 values from FMG JavaScript Alea PRNG with seed 'debug-123'
# You'll need to run FMG and capture these values
FMG_EXPECTED_VALUES = [
    # TODO: Replace with actual values from FMG
    # Run this in FMG browser console:
    # prng = new Alea('debug-123');
    # values = [];
    # for (let i = 0; i < 100; i++) values.push(prng());
    # console.log(JSON.stringify(values.slice(0, 100)));
]

def test_alea_compatibility():
    """Test that our Python AleaPRNG matches FMG JavaScript exactly."""
    
    # Create PRNG with same seed
    prng = AleaPRNG('debug-123')
    
    # Generate first 100 values
    python_values = []
    for i in range(100):
        python_values.append(prng.random())
    
    print("First 10 Python AleaPRNG values:")
    for i, val in enumerate(python_values[:10]):
        print(f"  [{i}]: {val}")
    
    if FMG_EXPECTED_VALUES:
        # Compare with FMG values
        print("\nComparing with FMG values...")
        mismatches = 0
        for i in range(min(len(python_values), len(FMG_EXPECTED_VALUES))):
            if abs(python_values[i] - FMG_EXPECTED_VALUES[i]) > 1e-15:
                print(f"MISMATCH at index {i}:")
                print(f"  Python: {python_values[i]}")
                print(f"  FMG:    {FMG_EXPECTED_VALUES[i]}")
                print(f"  Diff:   {python_values[i] - FMG_EXPECTED_VALUES[i]}")
                mismatches += 1
                if mismatches >= 5:
                    print("... stopping after 5 mismatches")
                    break
        
        if mismatches == 0:
            print("SUCCESS: All values match!")
        else:
            print(f"\nFAILED: {mismatches} mismatches found")
    else:
        print("\nTo complete this test:")
        print("1. Open FMG in browser")
        print("2. Open developer console (F12)")
        print("3. Run this code:")
        print("""
prng = new Alea('debug-123');
values = [];
for (let i = 0; i < 100; i++) values.push(prng());
console.log(JSON.stringify(values));
""")
        print("4. Copy the output array and paste it as FMG_EXPECTED_VALUES above")
        print("\nPython values for manual comparison:")
        print(f"python_values = {python_values[:20]}...")

if __name__ == "__main__":
    test_alea_compatibility()